import type { AgentRole } from '@/core';

export const ROLES: AgentRole[] = ['SuperAdmin', 'Admin', 'Manager', 'Employee', 'Guest'];

export const ROUTE_PERMISSIONS: Record<string, AgentRole[]> = {
  '/api/agents': ['SuperAdmin', 'Admin', 'Manager'],
  '/api/tasks': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/memory': ['SuperAdmin', 'Admin', 'Manager'],
  '/api/projects': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/calendar': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/documents': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/users': ['SuperAdmin', 'Admin'],
  '/api/mision001/clientes': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision001/oportunidades': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision001/visitas': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision001/presupuestos': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision001/presupuestos/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision002/proyectos': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision002/proyectos/activos': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision002/proyectos/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision003/events': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision003/events/recent': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision003/events/entity': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/contratos': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/contratos/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/facturas': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/cobros': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/kpis': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/expedientes': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/expedientes/proyecto': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/expedientes/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/documentos': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision004/documentos/validar': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/catalogo': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/plantillas': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/expediente-contratos': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/expediente-contratos/expediente': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/expediente-contratos/proyecto': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/expediente-contratos/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/kpis': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision006/timeline': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision007/colaboradores': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision007/colaboradores/update': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision007/colaboradores/associate': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision007/colaboradores/deactivate': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision007/kpis': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision009/servicios': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision009/asignaciones': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision009/asignaciones/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision009/kpis': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision010/subvenciones': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision010/subvenciones/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision010/vinculaciones': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision010/kpis': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision012/tareas': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision012/tareas/asignacion': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision012/tareas/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision012/kpis': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision013/colaboradores': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision013/colaboradores/validar': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision013/colaboradores/activar': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision013/colaboradores/estado': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision013/colaboradores/asociar-proyecto': ['SuperAdmin', 'Admin', 'Manager', 'Employee'],
  '/api/mision013/kpis': ['SuperAdmin', 'Admin', 'Manager', 'Employee']
};

export function canAccessRoute(role: AgentRole, route: string) {
  const allowedRoles = ROUTE_PERMISSIONS[route] ?? ['SuperAdmin'];
  return allowedRoles.includes(role);
}
